# Generated by Django 5.2.6 on 2025-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingregistration_registrationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='medical_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/pending/'),
        ),
    ]
