# Generated by Django 5.2.6 on 2025-09-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendingregistration_medical_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('ANDHRA_PRADESH', 'Andhra Pradesh'), ('ARUNACHAL_PRADESH', 'Arunachal Pradesh'), ('ASSAM', 'Assam'), ('BIHAR', 'Bihar'), ('CHHATTISGARH', 'Chhattisgarh'), ('GOA', 'Goa'), ('GUJARAT', 'Gujarat'), ('HARYANA', 'Haryana'), ('HIMACHAL_PRADESH', 'Himachal Pradesh'), ('JHARKHAND', 'Jharkhand'), ('KARNATAKA', 'Karnataka'), ('KERALA', 'Kerala'), ('MADHYA_PRADESH', 'Madhya Pradesh'), ('MAHARASHTRA', 'Maharashtra'), ('MANIPUR', 'Manipur'), ('MEGHALAYA', 'Meghalaya'), ('MIZORAM', 'Mizoram'), ('NAGALAND', 'Nagaland'), ('ODISHA', 'Odisha'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan'), ('SIKKIM', 'Sikkim'), ('TAMIL_NADU', 'Tamil Nadu'), ('TELANGANA', 'Telangana'), ('TRIPURA', 'Tripura'), ('UTTAR_PRADESH', 'Uttar Pradesh'), ('UTTARAKHAND', 'Uttarakhand'), ('WEST_BENGAL', 'West Bengal'), ('ANDAMAN_NICOBAR', 'Andaman & Nicobar Islands'), ('CHANDIGARH', 'Chandigarh'), ('DNH_DD', 'Dadra & Nagar Haveli and Daman & Diu'), ('DELHI_NCT', 'Delhi (NCT)'), ('JAMMU_KASHMIR', 'Jammu & Kashmir'), ('LADAKH', 'Ladakh'), ('LAKSHADWEEP', 'Lakshadweep'), ('PUDUCHERRY', 'Puducherry')], default='MAHARASHTRA', help_text='Indian state or union territory', max_length=40),
        ),
    ]
