# Generated by Django 5.2.6 on 2025-09-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstage',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizstage',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
