# Generated by Django 5.2.6 on 2025-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_quiz_is_active_quiz_uniq_one_active_quiz'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='quiz',
            name='uniq_one_active_quiz',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='exams_quiz_start_a_e3d4f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='exams_quiz_end_at_6c63b3_idx',
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_quiz'),
        ),
    ]
