# Generated by Django 5.2.6 on 2025-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_quiz_options_remove_quiz_uniq_one_active_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='no_ans',
            field=models.BooleanField(default=False),
        ),
    ]
