# Generated by Django 5.2.6 on 2025-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_attemptanswer_bookmark_attemptanswer_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
