# Generated by Django 5.2.6 on 2025-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_quizattempt_is_disqualified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='is_disqualified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
