# Generated by Django 5.2.6 on 2025-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_quizattempt_is_disqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstageattempt',
            name='is_disqualified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
