# Generated by Django 5.2.6 on 2025-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_quizstageattempt_is_disqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstage',
            name='is_negative_makring',
            field=models.BooleanField(default=False),
        ),
    ]
