# Generated by Django 5.2.6 on 2025-09-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_quizstage_mode_quizstage_rounds_required_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
