# Generated by Django 5.2.6 on 2025-09-17 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_round_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stageadmission',
            options={'ordering': ('-admitted_at', 'stage_id')},
        ),
        migrations.RemoveConstraint(
            model_name='stageadmission',
            name='uq_stage_admission_stage_user',
        ),
        migrations.RemoveField(
            model_name='round',
            name='is_buzzer',
        ),
        migrations.AddField(
            model_name='quizstage',
            name='SIngle_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stageadmission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_admissions', to='exams.team'),
        ),
        migrations.AlterField(
            model_name='stageadmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stageadmission',
            index=models.Index(fields=['stage', 'team'], name='exams_stage_stage_i_7e5faf_idx'),
        ),
        migrations.AddConstraint(
            model_name='stageadmission',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('stage', 'user'), name='uq_stage_admission_stage_user_v2'),
        ),
        migrations.AddConstraint(
            model_name='stageadmission',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('stage', 'team'), name='uq_stage_admission_stage_team_v2'),
        ),
        migrations.AddConstraint(
            model_name='stageadmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('team__isnull', True)), models.Q(('user__isnull', True), ('team__isnull', False)), _connector='OR'), name='ck_stage_admission_exactly_one_actor'),
        ),
    ]
