# Generated by Django 5.2.6 on 2025-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='video_url',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=models.FileField(default=1, upload_to='tutorials/videos/'),
            preserve_default=False,
        ),
    ]
